### PR TITLE
style: tweaks for request, FAQ and other pages

### PR DESCRIPTION
**Pull request by arslanashraf7**
## Related Ticket:
#5 

## What this PR Does?
- Updates the `Contact Us` button design on the home page
- Updated the `Submit Request` page design
- Updates the FAQ page listing design
- Updates some configurable values

**NOTE** The theme can be seen/tested live on https://mitxonlinesupporttest.zendesk.com/hc/en-us

## Screenshots

**HOMEPAGE DESKTOP**
screencapture-mitxonlinesupporttest-zendesk-hc-en-us-2021-12-29-18_46_21

**HOMEPAGE Mobile**
screencapture-mitxonlinesupporttest-zendesk-hc-en-us-2021-12-29-18_46_31

**NEW REQUEST DESKTOP**
screencapture-mitxonlinesupporttest-zendesk-hc-en-us-requests-new-2021-12-29-18_45_03

**NEW REQUEST MOBILE**
screencapture-mitxonlinesupporttest-zendesk-hc-en-us-requests-new-2021-12-29-18_45_14

**FAQ DESKTOP**
screencapture-mitxonlinesupporttest-zendesk-hc-en-us-articles-4413803845523-How-can-agents-leverage-knowledge-to-help-customers-2021-12-29-18_45_47

**HOMEPAGE MOBILE**
screencapture-mitxonlinesupporttest-zendesk-hc-en-us-articles-4413803845523-How-can-agents-leverage-knowledge-to-help-customers-2021-12-29-18_46_03

### CODE REVIEW

**Comment by arslanashraf7** [comment]
@briangrossman can you take a look at the screenshots and/or the test theme link that i added in the PR description. let me know if this looks good to you.

**Comment by briangrossman** [comment]
@arslanashraf7 
LGTM - where G = Great

One question: Why are there two `Subject` fields in the [Submit a Request](https://mitxonlinesupporttest.zendesk.com/hc/en-us/requests/new) page? 
image

**Comment by arslanashraf7** [comment]
> @arslanashraf7 LGTM - where G = Great
> 
> One question: Why are there two `Subject` fields in the [Submit a Request](https://mitxonlinesupporttest.zendesk.com/hc/en-us/requests/new) page? image

@briangrossman, I created an extra field in the form of inputs through Zendesk admin in [this](https://mitxonlinesupporttest.zendesk.com/hc/en-us) test deployment (Which I've now removed from the test account as well). This won't affect things in production.

**Review by umarmughal824 — APPROVED** [review]
:+1:

**Comment by arslanashraf7** [comment]
@briangrossman these changes are merged and you can deploy the latest theme from the main branch. Let me know if you see any other issues.

**Pull request merged**
