### PR TITLE
style: match the theme footer with MITxOnline App

### PR DESCRIPTION
**Pull request by arslanashraf7**
## Related Tickets
#1 , https://github.com/mitodl/mitxonline/issues/292

## What this PR does?
- Updates theme assets
- Updates theme styling for footer to match with MITxOnline
- Updates theme components

## How to test?
-  The best way for you would be to test it on the trial instance that I deployed. You can see it https://mitxonline-test-theme.zendesk.com/hc/en-us
- If you'd like to test it in depth then I can give you access to the test instance I created

## Screenshots
**DESKTOP**
Screenshot 2021-12-03 at 3 38 13 PM
Screenshot 2021-12-03 at 3 38 20 PM
**MOBILE**
Screenshot 2021-12-03 at 3 47 41 PM
Screenshot 2021-12-03 at 3 47 51 PM

### CODE REVIEW

**Comment by arslanashraf7** [comment]
@briangrossman Could you take a look at the screenshots? I've also published this theme on a test/trial instance [here](https://mitxonline-test.zendesk.com/hc/en-us).

**Comment by briangrossman** [comment]
@arslanashraf7 Screenshots look good to me!

**Review by umarmughal824 — CHANGES_REQUESTED** [review]
Same concerns on what i made for #4. Better to address those changes here and rebase #4 on it

**Comment by arslanashraf7** [comment]
> Same concerns on what i made for #4. Better to address those changes here and rebase #4 on it

@umarmughal824 As already mentioned on the PR(https://github.com/mitodl/mitxonline-zendesk-theme/pull/3) which is rebased on this. Since you reviewed that you won't need to review this one as it has already been reviewed in https://github.com/mitodl/mitxonline-zendesk-theme/pull/3.

**Comment by umarmughal824** [comment]
> > Same concerns on what i made for #4. Better to address those changes here and rebase #4 on it
> 
> @umarmughal824 As already mentioned on the PR(#3) which is rebased on this. Since you reviewed that you won't need to review this one as it has already been reviewed in #3. I'm inclined to close this one if you have no issues.

OK, that makes sense

**Comment by arslanashraf7** [comment]
Closing this PR since all these changes are already part of #4

**Pull request closed without merging**
