### PR TITLE
Sync the mitxonline Zendesk theme with the upstream.

### PR DESCRIPTION
**Pull request by mudassir-hafeez**
### What are the relevant tickets?

[#3839](https://github.com/mitodl/hq/issues/3839) 

### Description (What does it do?)
Here is the Testing URL of re-synced theme: ~~https://arbisoft7203.zendesk.com/hc/en-us~~ https://mitodlhelp.zendesk.com/hc/en-us

This PR syncs the mitxonline Zendesk theme with the upstream. It maintains the existing design sync and incorporates updates and features from the Zendesk upstream theme. To see a list of all the updates and features, please refer to the changelog [here](https://github.com/zendesk/copenhagen_theme/blob/master/CHANGELOG.md). Here are a few updates highlighted during testing:

- A clear search feature on multiple pages, retaining the feature for review, and disabled the existing search submit button on the homepage as it was conflicting with this feature. 
- A "Sign in" link for users, providing access to their profile, requests, and activities. This feature is also available on the mobile view.
  - Users can view all their requests and their statuses under "requests."
  - Users can view all their activities, such as following and contributions, such as article comments.
- Follow button for users to follow different sections such as announcement, FAQs, and etc

### How should this be manually tested?

1. Homepage Changes:

- Visit the [old mitxonline Zendesk home page](https://mitxonline.zendesk.com/hc/en-us) and compare it with the [new mitxonline Zendesk home page](https://mitodlhelp.zendesk.com/hc/en-us).
- Ensure that the clear search feature is functional on multiple pages.
- Confirm that the search submit button on the homepage is enabled and working.

2. Submit a Request Page:

- Navigate to the [old submit a request page](https://mitxonline.zendesk.com/hc/en-us/requests/new) and compare it with the [new submit a request page](https://mitodlhelp.zendesk.com/hc/en-us/requests/new).

- Ensure that the layout and functionality of the new submit a request page match the expected changes and incorporate new changes if any.

3. "Sign In" link:
- Confirm that the "Sign In" link is not visible in the test environment and will not be present when deployed to production or verify that the "Sign In" link is disabled in the header for both desktop and mobile views. 

Overall Testing:

- Conduct general testing of the Zendesk theme to ensure that all existing features are functioning correctly after the sync with the upstream.
- Test any other specific features or functionalities mentioned in the changelog or observed during the sync process.

### Screenshots (if appropriate):

**Old mitxonline zendesk home page:**
image

**New mitxonline zendesk home page:**
image

**Old submit a request page:**
image

**New submit a request page:**
image

**Old mitxonline zendesk categories page:**
image

**New mitxonline zendesk categories page:**
image

**Old mobile view:**
image

**New mobile view:**
image

**User profile drop down:**
End user profile drop down

### Additional Context

-  While working on this, there was no workflow for auditing URLs using Lighthouse before. Now it exists but is not yet configured. Should we configure or let it go?

- For now, disabled/skipped some jobs that did not exist before and require a decision on whether to keep them disabled or not. ~~One job, "Lint commit messages," is intentionally disabled because its purpose is to check commit conventions from the base SHA to the new pull request SHA. However, in our case (of making a pull request - sync upstream with the master branch), where there are many old commits in copenhagen_theme that don't follow commit conventions before that job was introduced, this job will fail. We can re-enable it to enforce commit convention rules after the sync-upstream-master branch is merged with master.~~ After the strategy change, this will now rely on our commits made to this fork. It took another effort to follow commit linting rules(as our most of the commits don't follow them) but somehow managed the linting rules by updating commit message type. Those commit messages were fixed while resolving conflicts. We will follow the same approach mentioned above (disabling and re-enabling it to enforce commit convention rules after the PR merge) for other repositories while syncing, if that's not the case.

### CODE REVIEW

**Comment by pdpinch** [comment]
This is looking pretty good. I have a couple of questions / comments:

- Can you create try creating some more articles so we can see a page layout like [this one](https://mitxonline.zendesk.com/hc/en-us/categories/4409603743259-About-MITx-Online)?
- Does the upstream theme remove the search button? I think that's an accessibility issues. 
- I presume the "Sign In" link in the header is a configuration option, and we won't see that when this is deployed to production. 
- I presume the follow button (for example, in the top right of [this page](https://arbisoft7203.zendesk.com/hc/en-us/sections/23447959789585-FAQ)) is a configuration option as well. I don't think we need that. 
- Can you set up the submit form to look more like [ours](https://mitxonline.zendesk.com/hc/en-us/requests/new)?

**Comment by mudassir-hafeez** [comment]
@pdpinch please use this test instance https://mitodl.zendesk.com/hc/en-us to review the following points as the old one has expired:

> Can you create try creating some more articles so we can see a page layout like [this one](https://mitxonline.zendesk.com/hc/en-us/categories/4409603743259-About-MITx-Online)?

I've created some articles. You can view them [here](https://mitodl.zendesk.com/hc/en-us/categories/13612369568796-About-MITx-Online) to compare with [this one](https://mitxonline.zendesk.com/hc/en-us/categories/4409603743259-About-MITx-Online).

> Does the upstream theme remove the search button? I think that's an accessibility issues.

On the upstream, the search button is disabled from the start. It was available on our theme as there is an attribute to enable it. However, it seemed like Zendesk did not handle the clear search feature along with the search button enabled. So, I've fixed it now. Please review it on the [home page](https://mitodl.zendesk.com/hc/en-us).
 

> I presume the "Sign In" link in the header is a configuration option, and we won't see that when this is deployed to production. 

Added a configuration option for the "Sign In" link in the header for desktop and mobile view. Now, we won't see that when this is deployed to production, and in the test instance as well.

> I presume the follow button (for example, in the top right of [this page](https://arbisoft7203.zendesk.com/hc/en-us/sections/23447959789585-FAQ)) is a configuration option as well. I don't think we need that. 

The follow button (for example, in the top right of [this page](https://mitodl.zendesk.com/hc/en-us/sections/13612382379292-Getting-Started)) is also available on our [theme section](https://mitxonline.zendesk.com/hc/en-us/sections/4409952404251-Getting-Started). So, we are good with that, I think.

> Can you set up the submit form to look more like [ours](https://mitxonline.zendesk.com/hc/en-us/requests/new)?

I set up two forms before for testing purposes, which appeared as a dropdown first. Now, I've kept it as one in the new instance. You can see the [submit form](https://mitodl.zendesk.com/hc/en-us/requests/new) to compare with [ours](https://mitxonline.zendesk.com/hc/en-us/requests/new).

**Comment by pdpinch** [comment]
Thank you for all the examples. I think this is good enough for now. 

We'll have to coordinate the deployment with the customer support team. But it doesn't look like this is passing tests yet.

**Comment by mudassir-hafeez** [comment]
> We'll have to coordinate the deployment with the customer support team. But it doesn't look like this is passing tests yet.

@pdpinch it seems like someone has added settings(codeQL)for that repo which was not previously. Here is the related [slack message](https://mitodl.slack.com/archives/G1VJY4CCV/p1713185676744399?thread_ts=1712927195.178919&cid=G1VJY4CCV) shared by you on this.  

I don't think, Ruby is being used in the theme which is why the check is failing. Also, is it necessary to enable these settings(CodeQL, CodeScanning) for a theme where we mainly customize designs and mostly rely on Zendesk? 

@arslanashraf7 would you please share your thoughts on this ^^?

For more context on disabling the checks, please refer to the `Additional Context` section mentioned in the PR description.

**Comment by arslanashraf7** [comment]
> > We'll have to coordinate the deployment with the customer support team. But it doesn't look like this is passing tests yet.
> 
> @pdpinch it seems like someone has added settings(codeQL)for that repo which was not previously. Here is the related [slack message](https://mitodl.slack.com/archives/G1VJY4CCV/p1713185676744399?thread_ts=1712927195.178919&cid=G1VJY4CCV) shared by you on this.
> 
> I don't think, Ruby is being used in the theme which is why the check is failing. Also, is it necessary to enable these settings(CodeQL, CodeScanning) for a theme where we mainly customize designs and mostly rely on Zendesk?
> 
> @arslanashraf7 would you please share your thoughts on this ^^?
> 
> For more context on disabling the checks, please refer to the `Additional Context` section mentioned in the PR description.

@mudassir-hafeez I think @blarghmatey recently mentioned that codeQL has been enabled for the organization and that's probably why that check is running in this repo as well. We can ignore that check based on what you have mentioned above.

**Review by asadali145 — APPROVED** [review]
The code looks good. Just a few things that I have noticed:

Request Page:
1. The last item in breadcrumbs is a link and points to `#`. Can we disable the link? This happens for all subpages.
2. We do not have red asterisks `*` for the required fields. Is this something that Zendesk removed or is it configurable?
Screenshot 2024-04-30 at 5 15 46 PM

Header:
1. The Header `Support Center` gets a:visited and is always red. Can we set it black as this is our custom link?
Screenshot 2024-04-30 at 5 19 13 PM

**Comment by mudassir-hafeez** [comment]
@asadali145, here are the responses after a quick verification of the copenhagen_theme with the master branch:

> The last item in breadcrumbs is a link and points to #. Can we disable the link? This happens for all subpages.

Regarding the last item in breadcrumbs being a link and pointing to "#", it seems that this behavior has been introduced in the upstream master. Here is a screenshot of the copenhagen_theme with the master branch for reference:
Screenshot 2024-04-30 at 6 38 49 PM

> We do not have red asterisks * for the required fields. Is this something that Zendesk removed or is it configurable?

As for the absence of red asterisks (*) for the required fields, it appears that Zendesk has removed them, and this change is not configurable. This modification was made some time ago. You can verify this behavior by visiting the following link(one of our zendesk themes): https://mitx-micromasters.zendesk.com/hc/en-us/requests or by viewing the screenshot of the copenhagen_theme with the master branch:

image


> The Header Support Center gets a:visited and is always red. Can we set it black as this is our custom link?

Zendesk has introduced a configuration option (visited_link_color) to address this. The default value for this option was #9358B0, which did not align with our branding. Therefore, set the default value to match the branding of the mitxoline-zendesk-theme. However, the choice of default color is flexible and can be adjusted as needed. If there is disagreement regarding the default visited link color, we can make the default color for this new configuration to black which can easily be changed from theme settings when required. Also providing screenshot of that feature of copenhagen_theme with master to verify:

image

**Please note** that the color will remain black if you haven't visited before or if you try to open the link in incognito mode.

**Comment by asadali145** [comment]
@mudassir-hafeez Thanks for looking into these options. I am good with all of them.

@pdpinch FYI, Please see the last 2 comments on this PR.
https://github.com/mitodl/mitxonline-zendesk-theme/pull/2#pullrequestreview-2031196822
https://github.com/mitodl/mitxonline-zendesk-theme/pull/2#issuecomment-2085471968

**Comment by pdpinch** [comment]
Thank you @asadali145 and @mudassir-hafeez. I am fine with the breadcrumb link being active and with the removal of the asterisk on the required fields. I hope that ZenDesk had a good reason for making those changes.

**Comment by mudassir-hafeez** [comment]
It seems we are good so far, and there are no pending request changes. I'm proceeding to squash the commits as discussed.
CC: @arslanashraf7

**Comment by mudassir-hafeez** [comment]
> We'll have to coordinate the deployment with the customer support team. 

@pdpinch, I am including you here for your reference. The Zendesk themes for MITx Online, Bootcamp, Micromasters, and OCW have been synchronized and are ready for deployment to the live instances.
CC: @arslanashraf7

**Pull request merged**
